### PR TITLE
Changed the w-20 img tag src as requested

### PR DESCRIPTION
**Pull request by shaalan-ahmed**

### CODE REVIEW

**Review by nitro56565 — CHANGES_REQUESTED** [review]
i still dont see the image, check the vercel preview its not visible.
image

**Comment by shaalan-ahmed** [comment]
can you confirm if this is the code snippet that needs changing in AmbulanceMainPage.jsx?
```
<div className="cursor-pointer" onClick={currentLocation}>
    <img className="w-20" src="../../../assets/current-location-svg.svg" alt="Current Location" />
</div>
```

**Comment by nitro56565** [comment]
> can you confirm if this is the code snippet that needs changing in AmbulanceMainPage.jsx?
> 
> ```
> <div className="cursor-pointer" onClick={currentLocation}>
>     Current Location
> </div>
> ```

yes

**Comment by shaalan-ahmed** [comment]
In no way i am trying to say that you are wrong but correct me if i say something stupid;
but i think that the src is right
```
src="../../../assets/current-location-svg.svg"
```

**Comment by nitro56565** [comment]
> In no way i am trying to say that you are wrong but correct me if i say something stupid; but i think that the src is right
> 
> ```
> ../../assets/current-location-svg.svg"
> ```

yes the src is right but its still not showing up the image it could possibly some other issue try finding that out

**Comment by shaalan-ahmed** [comment]
Sorry i can't find the error, i apologize

**Pull request closed without merging**
