### PR TITLE
Forgot password component added

### PR DESCRIPTION
**Pull request by surajb0710**
Please review and let me know if there is any issue. This is my very first PR to Open Source Project, once this is merged, will pick up other FE issues as well.

### CODE REVIEW

**Review by nitro56565 — CHANGES_REQUESTED** [review]
Hi @surajb0710 the forgot page UI looks good but there is no enter opt input field, there needs to be input field to enter the OTP and a button to validate as well.
so the whole process would be like the person will enter his number then he will receive an OTP on his phone he will enter that OTP on same page and will click on validate OTP then from backend he will receive another message on his phone with his password and on UI there should display a message that "OTP verified, Check SMS for password" else "Invalid OTP"

**Comment by nitro56565** [comment]
Hi @surajb0710 can I get the resolution asap as I have to start moving this project from react to react native by today evening

**Comment by surajb0710** [comment]
Hi sorry, I was away for some work. I have updated added the OTP input field and updated the page a little bit. I could not add the OTP trigger as its a backend and I am not exactly aware of backend for now.
Click here, has link to forgot password page, once the OTP trigger is added, same trigger needs to be added to that link.
I wanted to add the error message for empty phone number field, but could not figure that part out yet.
Also, I thought of adding the country code for phone numbers, but wanted to give you this much for now.

**Comment by nitro56565** [comment]
this looks good @surajb0710 , thank you for your contribution and congrats on your 1st PR merge

**Pull request merged**
