### PR TITLE
Phone Number Validation

### PR DESCRIPTION
**Pull request by SamikshaKadam19**
Phone Number Field Validation done for below pages:
1. Forgot Password Page
2. Signin Component

### CODE REVIEW

**Comment by nitro56565** [comment]
make sure not to forget to use -s for signoff while committing @SamikshaKadam19

**Review by nitro56565 — CHANGES_REQUESTED** [review]
Even after entering 10 digits and moving my focus it still shows me the error message which should not happen
Screenshot (14)
make the OTP digit in center and big and bolder as well
Screenshot (13)

the overall UI still seems a bit off please make changes according to user friendliness and make sure to test it on mobile devices as well

**Comment by SamikshaKadam19** [comment]
working on it

**Review by nitro56565 — APPROVED** [review]

**Review by nitro56565 — CHANGES_REQUESTED** [review]
If a user enters less than required phone number (10 digit) and then when he clicks on Request OTP if they are not 10 digits it should show an error message that enter 10 digit and as the user tries to change anything (even a single digit) in the input box the error message should go away. other than that everything looks good

**Pull request closed without merging**
